apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rgw-analysis-web.fullname" . }}-scripts
  labels:
{{ include "rgw-analysis-web.commonLabels" . | indent 4 }}
data:
  dataset-seeder.sh: |
{{ .Files.Get "files/dataset-seeder.sh" | indent 4 }}
  analyzer.sh: |
{{ .Files.Get "files/analyzer.sh" | indent 4 }}
  result-sync.sh: |
{{ .Files.Get "files/result-sync.sh" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rgw-analysis-web.fullname" . }}-runtime
  labels:
{{ include "rgw-analysis-web.componentLabels" (dict "root" . "component" "result-web") | indent 4 }}
data:
  S3_ENDPOINT_URL: {{ .Values.s3.endpointUrl | quote }}
  S3_BUCKET: {{ .Values.s3.bucket | quote }}
  AWS_DEFAULT_REGION: {{ .Values.s3.region | quote }}
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}
