{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rgw-analysis-web.serviceAccountName" . }}
  labels:
{{ include "rgw-analysis-web.commonLabels" . | indent 4 }}
automountServiceAccountToken: false
{{- end }}
